import 'package:flutter/material.dart';

class TermCondation extends StatefulWidget {
  const TermCondation({super.key});

  @override
  State<TermCondation> createState() => _TermCondationState();
}

class _TermCondationState extends State<TermCondation> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms & condition'),
        backgroundColor: Colors.grey[100],
        foregroundColor: Colors.black,
        elevation: 1,
        leading: GestureDetector(
          onTap: () => Navigator.pop(context),
          child: const Icon(Icons.arrow_back),
        ),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Nullam ac erat ante. Proin scelerisque luctus elit vel tincidunt. Nulla facilisi. Morbi vehicula dignissim nulla, at suscipit erat ultricies ut. Donec commodo sapien sit amet turpis ultricies, sit amet auctor justo scelerisque.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Nullam ac erat ante. Proin scelerisque luctus elit vel tincidunt. Nulla facilisi. Morbi vehicula dignissim nulla, at suscipit erat ultricies ut. Donec commodo sapien sit amet turpis ultricies, sit amet auctor justo scelerisque.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia odio vitae vestibulum vestibulum. Cras venenatis euismod malesuada. Nullam ac erat ante. Proin scelerisque luctus elit vel tincidunt. Nulla facilisi. Morbi vehicula dignissim nulla, at suscipit erat ultricies ut. Donec commodo sapien sit amet turpis ultricies, sit amet auctor justo scelerisque.',
              style:
                  TextStyle(fontSize: 16, letterSpacing: 0.1, wordSpacing: 0.2),
            ),
            SizedBox(height: 16),
            Text(
              'These Terms of Use (“Agreement”) sets forth a legally binding agreement between you and PassportParking, Inc. (“Company”).  This web site or application, including any software (including, without limitation, software, code, files, images, contained in or generated by the software, accompanying data, Boot ROM code and other embedded software), documentation and any accompanying fonts (collectively, the “Platform”) is provided pursuant to this Agreement. By accessing this Platform in any way, including, without limitation, browsing this Platform, using any information, and/or submitting information to Company, you agree to and are bound by the terms, conditions, policies and notices contained in this Agreement), including, but not limited to, conducting this transaction electronically, disclaimers of warranties, damage and remedy exclusions and limitations, and the applicability of the laws of England and Wales. Please read this Agreement carefully before using this Platform',
              style:
                  TextStyle(fontSize: 16, letterSpacing: 0.1, wordSpacing: 0.2),
            ),
            SizedBox(height: 16),
            Text(
              'Please read this Agreement carefully before using the Platform.  If you do not agree to the terms contained in this Agreement, then you may not use the Platform. Your use of the Platform constitutes your acknowledgment that you have the legal authority to bind yourself or any party you represent to, and your acceptance of, this Agreement.  You acknowledge that you have read and agree to be bound by this Agreement and to comply with all applicable laws, regulations and/or rules with regard to your use of the Platform.  You represent that you have the legal authority to bind yourself or any party you represent to this Agreement.',
              style:
                  TextStyle(fontSize: 16, letterSpacing: 0.1, wordSpacing: 0.2),
            ),
            SizedBox(height: 16),
            Text(
              'Company provides this Platform to you, subject to this Agreement.  This Platform, and any services performed, provided or enabled by or through this Platform and all the information, communications, scripting, photos, text, video, graphics, music, sounds, images, trademarks, logos, product and program names, and other materials and complications of the foregoing, that may be provided to you via this Platform (collectively “Content”) by Company or its content providers, are the property of Company and its content providers, and is protected in the United States and internationally under trademark, copyright, and other intellectual property laws, and are intended for the lawful use by registered users (as applicable) of this Platform.  You represent and warrant that you will use the Platform and Content only for the purposes permitted herein, that all information you submit is accurate and otherwise complies with this Agreement, and that you will promptly notify Company if any of your information changes.  Company makes no representation that the Platform or Content are appropriate or available for use in particular locations.You agree not to download, display or use any Content in any other manner that is likely to cause confusion among consumers, that disparages or discredits Company and/or its licensors, that dilutes the strength of Company or its licensors’ property, or that otherwise infringes Company or its licensors’ intellectual property rights',
              style:
                  TextStyle(fontSize: 16, letterSpacing: 0.1, wordSpacing: 0.2),
            ),
          ],
        ),
      ),
    );
  }
}
